### ISSUE TITLE
Provide Derek with necessary information to deploy Notification component to the AWS infrastructure 

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/pass-notification-services#18]
@derekbelrose please review the documentation here https://github.com/OA-PASS/pass-docker/tree/model-3.0#notification-services-environment and close this ticket if it provide sufficient information for deployment. If not please comment on what additional info would be needed.

**Comment by derekbelrose** [comment]
@emetsger Regarding: PASS_NOTIFICATION_QUEUE_EVENT_NAME

Would this follow the same naming scheme we are using with the other VirtualTopics?  So Consumer.notifications.VirtualTopic.pass.test-docker, etc?

We are currently following Consumer.*.VirtualTopic.pass.*-docker for all other queue names.

**Comment by emetsger** [comment]
@derekbelrose yes, as long as we're using ActiveMQ in test, demo, and production.

**Comment by derekbelrose** [comment]
I believe this is sufficient.  I may have additional questions, but this what I was looking for.
