### ISSUE TITLE
Specify the API for invoking Notification Link Services 

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/pass-notification-services#19]
If it can expressed as a Function<SubmissionEvent, URI>, or BiFunction<URI, Submission, URI> that might be ideal
i.e. URI toSend = nls.apply(submissionEvent.getLink(), submission)).

0.5 day FE

**Comment by birkland** [comment]
This is simply `Collection<Link> from(Submission submission, SubmissionEvent event)` to generate a collection of links, followed `.filter` and `.map` as appropriate, followed by `Collector<Link, Collection<Link>, String> toSerializedList()` to serialize as a JSON blob.
