### ISSUE TITLE
Design Notification Service Model 

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/pass-notification-services#2]
Account for: 

- Supported Notification Types
- Model class hierarchy
- Integrate with shared event model (e.g. SubmissionEvent)
- README

RET .5 day

**Comment by emetsger** [comment]
Initial model (it's small) is completed, but will need to be updated when `SubmissionEvent` is available in the PASS model.

Includes Jackson runtime configuration classes and parsing.
