### ISSUE TITLE
Specify the API of link processing components.

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/pass-notification-services#24]
2 day FE (Ideally, uniform and simple, like Function<SubmissionEvent, URI>, or BiFunction<URI, Submission, URI>)

**Comment by birkland** [comment]
The API is simply the stream API as applied to `org.dataconservancy.pass.notification.model.Link`  types.  In particular:
* `Predicate<Link>` for use in `.filter(predicate)`
* `UnaryOperator<Link>` for use in `.map(operator)`
