### ISSUE TITLE
Investigate spurious error when ITs connect to IMAP using SSL

### ISSUE THREAD

**Issue by emetsger** [eclipse-pass/pass-notification-services#45]
Sometimes the SimpleImapClient is not able to connect to the docker mailserver using SSL due to a read timeout error.

It's not clear why this happens.  Most of the time there is no issue.  This occurs locally on my Mac as well as on Travis.  Simply re-running the ITs until the read timeout error goes away is the work-around at the moment.

May be due to a bogus CN on the fake SSL cert presented by the docker mailserver (e.g. a reverse DNS lookup times out?)

**Comment by emetsger** [comment]
Still not resolved despite adding a proper self-signed cert to the IMAP server.

**Comment by emetsger** [comment]
Reviewed 1/7/19: this is still an issue, will require some deep debugging.  Not critical, but certainly annoying when PRs fail a build that should otherwise succeed.

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete. This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
