### ISSUE TITLE
Allow for SMTP TLS / SSL transport security to be configured

### ISSUE THREAD

**Issue by emetsger** [eclipse-pass/pass-notification-services#46]
Right now SMTP communication between NS and the mail relay hard coded.  Update the runtime configuration to allow for TLS and SMTPS.

**Comment by emetsger** [comment]
See `Mailer` bean definition in `SpringBootNotificationConfig`

**Comment by derekbelrose** [comment]
We will, most likely, need to use SMTPS/TLS for sending mail through AWS SES.
