### ISSUE TITLE
Whitelist filters repository URIs, rather than e-mail addresses

### ISSUE THREAD

**Issue by birkland** [eclipse-pass/pass-notification-services#55]
he problem, apparent in `RecipientAnalyzer`, is that for non "new user" scenarios, the whitelist is applied to submitter and preparer *URIs*, and has nothing to do with e-mail addresses.  So it's a whitelist of _Users to whom messages can be sent_, where each User is a fedora resource.

One fix is to produce a list of e-mail addresses in `RecipientAnalyzer` (which may involve looking at the submitter field of a submission, or looking up the e-mail field of a User), and apply the whitelist to the resulting e-mail addresses.  The e-mail transformation currently occurs in `org.dataconservancy.pass.notification.dispatch.impl.email.RecipientParser`

Another possible fix is to have `RecipientParser` apply the whitelist.

**Comment by emetsger** [comment]
Closed by #59.
