### ISSUE TITLE
Submission Details page shows "Loading files..." in the File section

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/pass-notification-services#56]
a list of uploaded files should be displayed instead.

**Steps to replicate**
Create a submission as a proxy submitter for a new submitter (`newSubmitter1`).  Look in the logs for the invite link, or look in the e-mail sent to `newSubmitter1`.  Follow the link as `newSubmitter1` (i.e. follow it in a new incognito window, and log in as `newSubmitter1` when prompted.  You should see a submission page with options to edit, cancel, submit, etc.  Look at files section.  It says `"Loafing files..."`, and never shows the files

**Comment by karenhanson** [comment]
This is an odd reaction to the `{uri}` in `/submissions/{uri}` being passed in as unencoded. When it is passed in as unencoded, Ember automatically encodes everything after `/submissions/`. This includes the `?userToken`. The result is, Ember attempts to search for files whose submission is e.g. `https://pass.local/fcrepo/rest/submissions/cc/f7/55/87/ccf75587-d828-4458-9deb-d1ed108d3896?userToken=BRO7QA373FK4LPNEJN3TRZUTO2B24EPQ6BHUJOOX3ZOWZEYMXFYRHMPK35THFHHTN4BCLRCXRIKEOX3AOPWCDIRLRCA6DK3LJXGQTSUKWAYZP23IWVMWF5IHQECOMNMVLHOKJTG2LZWNH7DCTZJZPOTYKM6HDJX65TE53ZGFNBYHGOMHPJB3XZET5HPOTFBQ52LHFJQJM24VQCVVNBVRXR5B3FDCATSYRVR7A2CXDP233VFOAIBAOW6LKBTIMGS7CHM4E3U7RHD5H4W2QQX5GUU5JQ`.
Here is a snippet of the log for notification services. Note that the link with userToken added is unencoded after the `https://pass.local/app/submissions/` 
```
18:18:06.759 [eListenerContainer-3] DEBUG [               SimpleWhitelist] - Any recipient will be whitelisted: the whitelist is empty.
18:18:06.788 [eListenerContainer-3] DEBUG [            UserTokenGenerator] - Attaching user token for <mailto:new.person@jhu.edu> to link <https://pass.local/app/submissions/https%3A%2F%2Fpass.local%2Ffcrepo%2Frest%2Fsubmissions%2F91%2F75%2Fba%2Fe6%2F9175bae6-7820-4b6e-93bd-4106f823c63a>
18:18:06.790 [eListenerContainer-3] INFO  [            UserTokenGenerator] - Generated invitation link <https://pass.local/app/submissions/https://pass.local/fcrepo/rest/submissions/91/75/ba/e6/9175bae6-7820-4b6e-93bd-4106f823c63a?userToken=BQZI6Z4JNHL4IGYHYSNUKOPOWXOJXZYP4IIB3L2OEQCJOXYQASK3NXLN5XVKQYG6FOGGJER5L36DK5YWQBZ7QDBH6NMSXE3IJ6FUP4NS5XBCBTFCBIBPDJW6BMLNHW4LZBVQOZJT5VXTZV7GN5BAJ6NAW2S7IWBL7YH47ULY7GU7NGO4M2JYJJX7VV4GLXYL2NGCTLRKS7YHYM6EUAVAY5SDC7HYXBL6PA2GITKD5GUPIBDH2C7BNXUAU7XEDFSPEPO253ESHI7HCU56AFGX56I> for <mailto:new.person@jhu.edu>
18:18:06.792 [eListenerContainer-3] DEBUG [                 LoggingAspect] - Dispatching notification to [mailto:new.person@jhu.edu], cc [] (Notification type: SUBMISSION_APPROVAL_INVITE, Event URI: http://fcrepo:8080/fcrepo/rest/submissionEvents/80/f2/60/8c/80f2608c-126c-4ae1-b7de-45da7e1a99e8, Resource URI: http://fcrepo:8080/fcrepo/rest/submissions/91/75/ba/e6/9175bae6-7820-4b6e-93bd-4106f823c63a)
```
