### ISSUE TITLE
Audit whitelist/email dispatch logic to consider varied (RFC-compliant) forms of email addresses

### ISSUE THREAD

**Issue by emetsger** [eclipse-pass/pass-notification-services#58]
[RFC 6068](https://tools.ietf.org/html/rfc6068) defines various encodings for `mailto` URIs.

Audit email dispatch and whitelist logic to insure non-trivial encodings for `mailto` URIs such as `<mailto:joe@example.com?cc=bob@example.com&body=hello>` or `<mailto:?to=joe@example.com&cc=bob@example.com&body=hello>` don't trip up dispatching of emails or whitelist application.

**Comment by emetsger** [comment]
Reviewed 1/7/19: still an issue, but not critical, as PASS doesn't use parameters in `mailto` URIs at the moment.

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete. This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
