### ISSUE TITLE
Update the handling of the global carbon copy handling to be consistent with whitelist handling

### ISSUE THREAD

**Issue by emetsger** [eclipse-pass/pass-notification-services#60]
Whitelist processing now occurs as part of the dispatch implementation (see #54 and #59).

Global CC handling should either occur in the dispatch implementation, or the configuration format should be updated to use URIs (e.g. `mailto:global-cc-address@mail.org` vs `global-cc-address@mail.org`).

**Comment by emetsger** [comment]
Reviewed 1/7/19: still an issue, not critical to fix.

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete. This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
