### ISSUE TITLE
Cut a release of notification services

### ISSUE THREAD

**Issue by emetsger** [eclipse-pass/pass-notification-services#61]
An official release of notification services should be cut before moving to the demo environment.

**Comment by htpvu** [comment]
@emetsger we will most likely deploy ns to demo tomorrow 11/14/2018. we should cut NS release today then?

**Comment by emetsger** [comment]
@htpvu sounds good!  Should be doable!

**Comment by htpvu** [comment]
closed by https://github.com/OA-PASS/pass-docker/pull/167
