### ISSUE TITLE
Allow for customization of the SubmissionEvent types that NS will respond to.

### ISSUE THREAD

**Issue by emetsger** [eclipse-pass/pass-notification-services#64]
Right now if someone wishes to ignore submitted or cancelled events (i.e. they don't want Notifications to be emitted based on cancelling or performing a submission) it is not easy to do so.  

Update NS to allow that to be configured at runtime.

**Comment by emetsger** [comment]
Reviewed 1/17/19: still an issue.  Whether or not this is addressed depends on implementation requirements.

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete. This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
